//! C# declare-mode extraction core (labelle-declare-csharp — the CoreCLR-family
//! member of the cross-runner declare contract, rust's / crystal's twin;
//! labelle-scripting#27, labelle-engine#743, RFC-LANGUAGE-PLUGINS §4/§7).
//!
//! C# is compiled, so — like tools/declare-rs and tools/declare-crystal, and
//! unlike the lua/ruby/ts extractors (which load a source string into an
//! embedded VM and read back the recorded declarations) — this one is a
//! COMPILE-AND-RUN PROBE: it stages a tiny C# console program under the
//! assembler-supplied cache dir, `dotnet build`s it, and runs it. The mechanism
//! is the assembler's blind spot by design (rev 17): to the assembler this is
//! just an exe that reads declaration files + a cache dir and prints schema
//! JSON; that it happens to shell `dotnet` is internal here.
//!
//! The staged program (all under <cache>/probe/):
//!   Declare.cs        — the SHIPPED native-csharp/src/Declare.cs (embedded at
//!                       build time, so the probe carries the exact declare
//!                       surface/emitter the tool was built against)
//!   decl_NNNN.cs      — each declaration file VERBATIM (NNNN = zero-padded
//!                       argv index). No prelude is injected: the declare
//!                       surface (`[LabelleComponent]`, `Vec2`, …) lives in the
//!                       GLOBAL namespace, so a game's components/*.cs compile
//!                       with NO `using` — tests/declare_csharp_tool.zig's
//!                       drift pin proves that absence.
//!   Program.cs        — generated: `Console.Out.Write(LabelleDeclare.EmitSchema())`
//!   probe.csproj      — generated: a net7.0 Exe listing the .cs files as
//!                       EXPLICIT, ORDERED <Compile> items (Declare.cs, then
//!                       decl_NNNN in argv order, then Program.cs) with
//!                       EnableDefaultCompileItems off — so Roslyn emits the
//!                       records' TypeDefs in file order then source order, and
//!                       the emitter's metadata-token sort reproduces
//!                       components-then-events / declaration order,
//!                       platform-independently (a filesystem glob order would
//!                       not).
//!
//! Ordering: the assembler passes components/*.cs before events/*.cs (argv
//! order), the csproj lists them in that order, so each `[LabelleComponent]` /
//! `[LabelleEvent]` record's TypeDef token increases in argv-then-source order —
//! components-then-events falls out for free (the emitter keeps a separate
//! metadata-token-sorted list per kind).
//!
//! Error policy: extraction is a BUILD step — a dotnet build failure aborts with
//! the compiler's output (`Outcome.failure`); there is no half-success. csc's
//! diagnostics carry the `decl_NNNN.cs:line` location (the staged file, whose
//! content is the game file verbatim) — enough to point the developer at the
//! offending declaration.

const std = @import("std");

/// The SHIPPED Labelle declare surface, embedded at build time (build.zig
/// anonymous import) so the tool is self-contained and carries the exact
/// surface/emitter it was built against.
const declare_cs_source = @embedFile("csharp_declare_src");

/// The generated probe entry point.
const program_cs =
    \\// Generated by labelle-declare-csharp (labelle-scripting#27). Do not edit.
    \\System.Console.Out.Write(LabelleDeclare.EmitSchema());
    \\
;

/// The probe assembly name (also the built .dll stem run below).
const probe_assembly = "labelle_declare_csharp_probe";

/// One declaration file to extract: `path` names it in usage/read errors;
/// `source` is its full text, staged verbatim.
pub const Input = struct {
    path: []const u8,
    source: []const u8,
};

/// Either the schema JSON (one compact line, no trailing newline) or the first
/// failure, as a printable message. The active slice is owned by the caller
/// (allocated with the `run` allocator).
pub const Outcome = union(enum) {
    schema: []u8,
    failure: []u8,

    pub fn deinit(self: Outcome, allocator: std.mem.Allocator) void {
        switch (self) {
            .schema, .failure => |s| allocator.free(s),
        }
    }
};

pub const Error = error{
    /// Staging the probe program under the cache dir failed (mkdir/write) — an
    /// environment problem (bad cache dir, disk), never a user-script problem.
    ProbeStage,
    /// dotnet could not be spawned, or its stdout/stderr could not be read — a
    /// toolchain/environment problem (the .NET SDK missing from PATH, pipe
    /// error).
    ProbeSpawn,
    OutOfMemory,
};

/// Stage the probe program under `cache_dir`, `dotnet build`s it (Release; the
/// persistent cache buys the warm incremental rebuild), run the built assembly,
/// and return its schema JSON — or the first failure. See the module doc for
/// the staging layout and ordering contract.
pub fn run(
    allocator: std.mem.Allocator,
    io: std.Io,
    environ_map: *std.process.Environ.Map,
    cache_dir: []const u8,
    inputs: []const Input,
) Error!Outcome {
    const cwd = std.Io.Dir.cwd();

    const probe_dir = std.fs.path.join(allocator, &.{ cache_dir, "probe" }) catch return error.OutOfMemory;
    defer allocator.free(probe_dir);
    cwd.createDirPath(io, probe_dir) catch return error.ProbeStage;

    // The shipped declare surface (embedded verbatim).
    writeUnder(cwd, io, allocator, probe_dir, "Declare.cs", declare_cs_source) catch return error.ProbeStage;
    // The generated entry point.
    writeUnder(cwd, io, allocator, probe_dir, "Program.cs", program_cs) catch return error.ProbeStage;

    // One staged module per input (game file verbatim) + the generated csproj
    // listing them as EXPLICIT, ORDERED <Compile> items (argv order).
    var compile_items: std.ArrayList(u8) = .empty;
    defer compile_items.deinit(allocator);
    try compile_items.appendSlice(allocator, "    <Compile Include=\"Declare.cs\" />\n");
    for (inputs, 0..) |input, i| {
        var namebuf: [32]u8 = undefined;
        const file_name = std.fmt.bufPrint(&namebuf, "decl_{d:0>4}.cs", .{i}) catch return error.OutOfMemory;
        writeUnder(cwd, io, allocator, probe_dir, file_name, input.source) catch return error.ProbeStage;
        const item = std.fmt.allocPrint(allocator, "    <Compile Include=\"{s}\" />\n", .{file_name}) catch return error.OutOfMemory;
        defer allocator.free(item);
        try compile_items.appendSlice(allocator, item);
    }
    try compile_items.appendSlice(allocator, "    <Compile Include=\"Program.cs\" />\n");

    const csproj = std.fmt.allocPrint(allocator,
        \\<Project Sdk="Microsoft.NET.Sdk">
        \\  <PropertyGroup>
        \\    <OutputType>Exe</OutputType>
        \\    <TargetFramework>net7.0</TargetFramework>
        \\    <AssemblyName>{s}</AssemblyName>
        \\    <ImplicitUsings>enable</ImplicitUsings>
        \\    <Nullable>enable</Nullable>
        \\    <LangVersion>latest</LangVersion>
        \\    <InvariantGlobalization>true</InvariantGlobalization>
        \\    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
        \\    <Deterministic>true</Deterministic>
        \\  </PropertyGroup>
        \\  <ItemGroup>
        \\{s}  </ItemGroup>
        \\</Project>
        \\
    , .{ probe_assembly, compile_items.items }) catch return error.OutOfMemory;
    defer allocator.free(csproj);
    writeUnder(cwd, io, allocator, probe_dir, "probe.csproj", csproj) catch return error.ProbeStage;

    const csproj_path = std.fs.path.join(allocator, &.{ probe_dir, "probe.csproj" }) catch return error.OutOfMemory;
    defer allocator.free(csproj_path);
    const bin_dir = std.fs.path.join(allocator, &.{ cache_dir, "bin" }) catch return error.OutOfMemory;
    defer allocator.free(bin_dir);

    // Build the probe. MSBuild noise goes to this call's stdout/stderr, which we
    // ignore on success — only the RUN step's stdout is the schema.
    const build_argv = [_][]const u8{
        "dotnet",    "build",
        csproj_path, "-c",
        "Release",   "--nologo",
        "-v",        "quiet",
        "-o",        bin_dir,
    };
    const build_res = std.process.run(allocator, io, .{
        .argv = &build_argv,
        .environ_map = environ_map,
    }) catch return error.ProbeSpawn;
    defer allocator.free(build_res.stdout);
    defer allocator.free(build_res.stderr);
    if (build_res.term != .exited or build_res.term.exited != 0) {
        // Surface dotnet's diagnostics — MSBuild prints errors to stdout, so
        // include both streams; they carry the staged decl_NNNN.cs:line.
        const msg = std.fmt.allocPrint(
            allocator,
            "labelle-declare-csharp: dotnet build failed:\n{s}\n{s}",
            .{ build_res.stdout, build_res.stderr },
        ) catch return error.OutOfMemory;
        return .{ .failure = msg };
    }

    // Run the built assembly; its stdout is the schema JSON (no trailing
    // newline — Program.cs uses Write, not WriteLine).
    const dll_path = std.fmt.allocPrint(allocator, "{s}/{s}.dll", .{ bin_dir, probe_assembly }) catch return error.OutOfMemory;
    defer allocator.free(dll_path);
    const run_res = std.process.run(allocator, io, .{
        .argv = &.{ "dotnet", dll_path },
        .environ_map = environ_map,
    }) catch return error.ProbeSpawn;
    defer allocator.free(run_res.stdout);
    defer allocator.free(run_res.stderr);
    if (run_res.term != .exited or run_res.term.exited != 0) {
        const msg = std.fmt.allocPrint(
            allocator,
            "labelle-declare-csharp: probe run failed:\n{s}",
            .{run_res.stderr},
        ) catch return error.OutOfMemory;
        return .{ .failure = msg };
    }

    // Trim any trailing newline; main.zig re-adds one (the labelle-declare
    // contract: schema, one line, then a newline).
    const trimmed = std.mem.trimEnd(u8, run_res.stdout, "\r\n");
    return .{ .schema = try allocator.dupe(u8, trimmed) };
}

/// Write `data` to `<parent>/<name>`, joining the path with the run allocator.
fn writeUnder(
    dir: std.Io.Dir,
    io: std.Io,
    allocator: std.mem.Allocator,
    parent: []const u8,
    name: []const u8,
    data: []const u8,
) !void {
    const path = try std.fs.path.join(allocator, &.{ parent, name });
    defer allocator.free(path);
    try dir.writeFile(io, .{ .sub_path = path, .data = data });
}
