//! mruby 3.4 state management for the `ruby` sub-module.
//!
//! The C API is hand-declared (the lua module's pattern) — no @cImport.
//! Two mruby-specific twists make that workable:
//!   - `mrb_value` is only ABI-mirrorable in the UNBOXED representation,
//!     so the vendored build pins MRB_NO_BOXING (+ MRB_INT64): the value
//!     is then the 16-byte {union, tag} struct in include/mruby/boxing_no.h,
//!     mirrored 1:1 by `c.Value` below. No-boxing also keeps full-width
//!     i64 integers AND floats immediate (no heap RInteger/RFloat), which
//!     the u64-id fidelity and zero-alloc stories both lean on.
//!   - the few APIs that are macros over mrb_state internals (GC arena,
//!     mrb->exc, RSTRING_*/RARRAY_*, mrbc_context bitfields) are wrapped
//!     as flat functions in src/ruby/shim.c, compiled with the vendored
//!     sources; `mrb_state` stays opaque on the Zig side.
//!
//! Error policy (the load-bearing part, mirroring src/lua/vm.zig): every
//! entry into ruby is a TOP-LEVEL mruby entry — mrb_load_nstring_cxt and
//! mrb_funcall_argv called with no protecting VM frame catch script
//! exceptions internally and park them in mrb->exc instead of unwinding
//! through our frames (verified against the vendored build). After each
//! entry the VM checks the slot, logs "<class>: <message>" plus the
//! exception's backtrace through labelle_log, clears it, and moves on — a
//! broken behavior script must NEVER kill the game tick. Boot-point
//! failures are stricter, exactly like lua: a chunk body that raises
//! (loadScript) or an `init` that raises (evictScript, driven by the
//! shared Controller) evicts the script — hooks, handlers and controllers
//! it registered are purged (prelude `Labelle.__evict_script`), so a
//! half-initialized script never receives `update`/`deinit`.
//!
//! Script isolation: mruby has no lua-style per-chunk _ENV — top-level
//! `def init/update/deinit` land as private methods on Object, shared by
//! everyone. The prelude's harvest protocol restores per-script isolation:
//! after each chunk body runs, `Labelle.__harvest` moves any freshly
//! defined hook methods to per-script aliased names (and removes the
//! originals), then dispatches them against a per-script receiver object —
//! so two scripts both defining `update` never collide, and each script's
//! @ivars live on its own receiver (init sets them, update reads them).
//!
//! Current-script tracking: around EVERY entry from the VM into script
//! code — the chunk body, each harvested hook, each controller lifecycle
//! call and each event handler — the global $__labelle_current_script is
//! stamped with the script's name (as a Symbol; symbols are immediate, so
//! per-tick stamping allocates nothing) and cleared after. It is the
//! VM-truth answer to "whose code is running": `Labelle.on` reads it to
//! record handler ownership and `Labelle.__register_controller` to record
//! controller ownership. Ownership can NOT be derived from caller
//! inspection — a helper method closing over the registration call would
//! attribute to the wrong frame; the stamp survives aliasing, helper
//! indirection and cross-script calls (the lua module's hard-won rule).
//!
//! GC discipline: mruby's arena (the root set for objects born inside a C
//! extension frame) is saved and restored around every VM entry — the
//! classic mruby-embedding overflow guard, here also the proof surface for
//! the zero-alloc tests (arena index stable across ticks = no per-tick
//! object-count growth).

const std = @import("std");
const contract = @import("../contract.zig");

/// Hand-declared mruby 3.4 C API — just the slice this plugin uses.
/// Real MRB_API functions only; macro-shaped APIs come from shim.c.
pub const c = struct {
    pub const State = opaque {};
    pub const RClass = opaque {};
    pub const Context = opaque {}; // mrbc_context, field access via shim

    pub const Int = i64; // mrb_int under MRB_INT64
    pub const Sym = u32; // mrb_sym
    pub const Bool = u8; // mrb_bool
    pub const Aspec = u32; // mrb_aspec

    /// enum mrb_vtype, generated by MRB_VTYPE_FOREACH in
    /// include/mruby/value.h — order is ABI (the tt tag below).
    pub const VType = enum(c_int) {
        false = 0,
        true,
        symbol,
        undef,
        free,
        float,
        integer,
        cptr,
        object,
        class,
        module,
        sclass,
        hash,
        cdata,
        exception,
        iclass,
        proc,
        array,
        string,
        range,
        env,
        fiber,
        strukt,
        istruct,
        brk,
        complex,
        rational,
        bigint,
        backtrace,
        _,
    };

    /// mrb_value under MRB_NO_BOXING (include/mruby/boxing_no.h): a tagged
    /// union passed by value. Integers, floats, symbols, nil/true/false are
    /// all immediate — only the pointer arm references the GC heap.
    pub const Value = extern struct {
        value: extern union {
            f: f64,
            p: ?*anyopaque,
            i: Int,
            sym: Sym,
        },
        tt: VType,

        pub fn nil() Value {
            return .{ .value = .{ .i = 0 }, .tt = .false };
        }
        pub fn boolean(b: bool) Value {
            return .{ .value = .{ .i = 1 }, .tt = if (b) .true else .false };
        }
        pub fn int(i: Int) Value {
            return .{ .value = .{ .i = i }, .tt = .integer };
        }
        pub fn float(f: f64) Value {
            return .{ .value = .{ .f = f }, .tt = .float };
        }
        pub fn symbol(s: Sym) Value {
            return .{ .value = .{ .sym = s }, .tt = .symbol };
        }
        /// SET_OBJ_VALUE for a known-module RClass* (the Labelle module).
        pub fn module(p: *RClass) Value {
            return .{ .value = .{ .p = p }, .tt = .module };
        }

        pub fn isNil(v: Value) bool {
            return v.tt == .false and v.value.i == 0;
        }
        pub fn truthy(v: Value) bool {
            return v.tt != .false;
        }
    };

    /// mrb_func_t — the C function shape behind module functions.
    pub const Func = *const fn (?*State, Value) callconv(.c) Value;

    // State lifecycle.
    pub extern fn mrb_open() ?*State;
    pub extern fn mrb_close(mrb: ?*State) void;

    // Compile + load (mruby-compiler gem, include/mruby/compile.h).
    // NOTE mruby 3.4 renamed the mrbc_* context API to mrb_ccontext_*
    // (the old spellings survive only as header macros) — hand-declared
    // externs must target the REAL symbols.
    pub extern fn mrb_ccontext_new(mrb: ?*State) ?*Context;
    pub extern fn mrb_ccontext_free(mrb: ?*State, cxt: ?*Context) void;
    pub extern fn mrb_ccontext_filename(mrb: ?*State, cxt: ?*Context, s: [*:0]const u8) ?[*:0]const u8;
    pub extern fn mrb_load_nstring_cxt(mrb: ?*State, s: [*]const u8, len: usize, cxt: ?*Context) Value;

    // Calling + interning.
    pub extern fn mrb_funcall_argv(mrb: ?*State, val: Value, name: Sym, argc: Int, argv: ?[*]const Value) Value;
    pub extern fn mrb_intern(mrb: ?*State, s: [*]const u8, len: usize) Sym;
    pub extern fn mrb_sym_name_len(mrb: ?*State, sym: Sym, len: ?*Int) ?[*]const u8;
    // NOTE deliberately NOT declared: mrb_protect / mrb_protect_error.
    // Every entry this module makes into ruby is a TOP-LEVEL one
    // (mrb->jmp == NULL), where mrb_load_*/mrb_funcall_* already catch
    // script exceptions into mrb->exc instead of unwinding — the
    // protect-wrapping the RFC prescribes is that protocol here, and
    // per-handler isolation is ruby-level begin/rescue in the prelude.

    // Module + method definition.
    pub extern fn mrb_define_module(mrb: ?*State, name: [*:0]const u8) ?*RClass;
    pub extern fn mrb_define_module_function(mrb: ?*State, cla: ?*RClass, name: [*:0]const u8, fun: Func, aspec: Aspec) void;
    pub extern fn mrb_get_args(mrb: ?*State, format: [*:0]const u8, ...) Int;

    // Values: construction and reading (functions only — immediates are
    // built directly on `Value`).
    pub extern fn mrb_str_new(mrb: ?*State, p: ?[*]const u8, len: Int) Value;
    pub extern fn mrb_ary_new_capa(mrb: ?*State, capa: Int) Value;
    pub extern fn mrb_ary_push(mrb: ?*State, ary: Value, elem: Value) void;
    /// The symbol behind the mrb_ary_ref(mrb, ...) header macro — note it
    /// takes no mrb_state.
    pub extern fn mrb_ary_entry(ary: Value, offset: Int) Value;
    pub extern fn mrb_hash_new_capa(mrb: ?*State, capa: Int) Value;
    pub extern fn mrb_hash_set(mrb: ?*State, hash: Value, key: Value, val: Value) void;
    pub extern fn mrb_hash_get(mrb: ?*State, hash: Value, key: Value) Value;
    pub extern fn mrb_hash_keys(mrb: ?*State, hash: Value) Value;
    pub extern fn mrb_obj_classname(mrb: ?*State, obj: Value) [*:0]const u8;

    // Globals (the $__labelle_current_script stamp; read from ruby only).
    pub extern fn mrb_gv_set(mrb: ?*State, sym: Sym, val: Value) void;

    // Raising from inside a module-function shim (longjmps to the VM —
    // the standard protocol; our shim frames hold no defers).
    pub extern fn mrb_exc_get_id(mrb: ?*State, name: Sym) ?*RClass;
    pub extern fn mrb_raise(mrb: ?*State, cla: ?*RClass, msg: [*:0]const u8) noreturn;

    // src/ruby/shim.c — macro-shaped APIs as flat functions.
    pub extern fn labelle_mrb_gc_arena_save(mrb: ?*State) c_int;
    pub extern fn labelle_mrb_gc_arena_restore(mrb: ?*State, idx: c_int) void;
    pub extern fn labelle_mrb_gc_live(mrb: ?*State) usize;
    pub extern fn labelle_mrb_gc_set_disabled(mrb: ?*State, disabled: Bool) void;
    pub extern fn labelle_mrb_exc_get(mrb: ?*State) Value;
    pub extern fn labelle_mrb_exc_clear(mrb: ?*State) void;
    pub extern fn labelle_mrbc_capture_errors(cxt: ?*Context, on: Bool) void;
    pub extern fn labelle_mrb_str_ptr(s: Value) [*]const u8;
    pub extern fn labelle_mrb_str_len(s: Value) Int;
    pub extern fn labelle_mrb_ary_len(a: Value) Int;
};

/// Global stamped with the executing script's name-symbol (nil between
/// entries) — see the module doc's current-script tracking section.
const CURRENT_SCRIPT_GLOBAL = "$__labelle_current_script";

/// Longest accepted script name for the mrbc filename buffer ("<name>" is
/// what backtrace lines print as the file). Longer names truncate.
const FILENAME_CAP = 128;

/// Cap for one formatted error log line. Backtraces can outgrow anything;
/// truncation beats a heap allocation inside the error path.
const ERROR_LOG_CAP = 2048;

/// Format + route one error line through the host's log sink.
fn logError(context: []const u8, text: []const u8) void {
    var buf: [ERROR_LOG_CAP]u8 = undefined;
    var w = std.Io.Writer.fixed(&buf);
    if (context.len > 0)
        w.print("[ruby] {s}: {s}", .{ context, text }) catch {}
    else
        w.print("[ruby] {s}", .{text}) catch {};
    const line = w.buffered();
    contract.labelle_log(line.ptr, line.len);
}

/// One embedded mruby VM. Carries the handful of pre-interned symbols the
/// per-tick dispatch path needs, so steady-state ticking interns nothing.
pub const Vm = struct {
    mrb: *c.State,
    labelle_module: *c.RClass,
    sym_current_script: c.Sym,
    sym_call_hook: c.Sym,
    sym_evict_script: c.Sym,
    sym_message: c.Sym,
    sym_backtrace: c.Sym,

    pub fn init() error{RubyStateInit}!Vm {
        const mrb = c.mrb_open() orelse return error.RubyStateInit;
        // The Labelle module exists from birth so bindings.install can hang
        // the raw shims off it and the prelude can reopen it.
        const mod = c.mrb_define_module(mrb, "Labelle") orelse {
            c.mrb_close(mrb);
            return error.RubyStateInit;
        };
        return .{
            .mrb = mrb,
            .labelle_module = mod,
            .sym_current_script = c.mrb_intern(mrb, CURRENT_SCRIPT_GLOBAL, CURRENT_SCRIPT_GLOBAL.len),
            .sym_call_hook = c.mrb_intern(mrb, "__call_hook", "__call_hook".len),
            .sym_evict_script = c.mrb_intern(mrb, "__evict_script", "__evict_script".len),
            .sym_message = c.mrb_intern(mrb, "message", "message".len),
            .sym_backtrace = c.mrb_intern(mrb, "backtrace", "backtrace".len),
        };
    }

    /// Close the VM. mruby's GC releases every script, receiver, handler
    /// and binding — this is the whole teardown story.
    pub fn close(self: Vm) void {
        c.mrb_close(self.mrb);
    }

    /// Compile + run an anonymous prelude-level chunk (real top level, no
    /// harvest) — how bindings.install runs prelude.rb. Returns false
    /// (logged) on compile or runtime error.
    pub fn runChunk(self: Vm, chunkname: [*:0]const u8, source: []const u8) bool {
        const arena = c.labelle_mrb_gc_arena_save(self.mrb);
        defer c.labelle_mrb_gc_arena_restore(self.mrb, arena);
        const cxt = c.mrb_ccontext_new(self.mrb);
        defer c.mrb_ccontext_free(self.mrb, cxt);
        _ = c.mrb_ccontext_filename(self.mrb, cxt, chunkname);
        c.labelle_mrbc_capture_errors(cxt, 1);
        _ = c.mrb_load_nstring_cxt(self.mrb, source.ptr, source.len, cxt);
        return !self.logPendingException(std.mem.span(chunkname));
    }

    /// Compile + run one registered script chunk, then harvest its
    /// top-level hooks into per-script storage (see the module doc). The
    /// mrbc filename is the script name, so every backtrace line reads
    /// "<name>:<line>". Returns false (logged) on any failure — and evicts
    /// whatever the failing body managed to register (handlers,
    /// controllers) before it raised, so nothing keeps firing into
    /// half-initialized state.
    pub fn loadScript(self: Vm, name: []const u8, source: [:0]const u8) bool {
        const mrb = self.mrb;
        const arena = c.labelle_mrb_gc_arena_save(mrb);
        defer c.labelle_mrb_gc_arena_restore(mrb, arena);

        var namebuf: [FILENAME_CAP]u8 = undefined;
        const n = @min(name.len, namebuf.len - 1);
        @memcpy(namebuf[0..n], name[0..n]);
        namebuf[n] = 0;
        const filename: [*:0]const u8 = @ptrCast(&namebuf);

        const cxt = c.mrb_ccontext_new(mrb);
        defer c.mrb_ccontext_free(mrb, cxt);
        _ = c.mrb_ccontext_filename(mrb, cxt, filename);
        c.labelle_mrbc_capture_errors(cxt, 1);

        const name_sym = c.mrb_intern(mrb, name.ptr, name.len);

        // The chunk body is a VM→script entry: stamp the current script so
        // `Labelle.on` / controller definitions at body scope attribute
        // their registrations here.
        self.setCurrentScript(name_sym);
        _ = c.mrb_load_nstring_cxt(mrb, source.ptr, source.len, cxt);
        self.setCurrentScript(null);
        if (self.logPendingException(name)) {
            // The body failed part-way: anything it registered before the
            // raise (chunk-scope Labelle.on, a controller class) must not
            // outlive it. Harvest never ran, so no hooks to remove — the
            // prelude purge covers handlers + controllers.
            _ = self.callLabelleSym(self.sym_evict_script, &.{c.Value.symbol(name_sym)}, name);
            return false;
        }

        // Move freshly defined top-level init/update/deinit onto this
        // script's private record (+ receiver). A raising harvest is a
        // prelude bug, but treat it like a body failure: log + evict.
        const harvest_sym = c.mrb_intern(mrb, "__harvest", "__harvest".len);
        if (!self.callLabelleSym(harvest_sym, &.{c.Value.symbol(name_sym)}, name)) {
            _ = self.callLabelleSym(self.sym_evict_script, &.{c.Value.symbol(name_sym)}, name);
            return false;
        }
        return true;
    }

    /// Quarantine a script whose `init` failed: purge its harvested hooks,
    /// event handlers and controllers (prelude-side `__evict_script`), and
    /// log the eviction once — the init backtrace alone would not explain
    /// why the script went silent afterwards.
    pub fn evictScript(self: Vm, name: []const u8) void {
        const name_sym = c.mrb_intern(self.mrb, name.ptr, name.len);
        _ = self.callLabelleSym(self.sym_evict_script, &.{c.Value.symbol(name_sym)}, name);
        logError(name, "init failed — script evicted; update/deinit will not run");
    }

    /// Call `hook` ("init"/"update"/"deinit") of the script registered as
    /// `script_name`, passing `dt` when given. Dispatch rides the
    /// prelude's `Labelle.__call_hook(name_sym, hook_sym, dt)`, which
    /// looks the harvested method up in the script's OWN record — another
    /// script's same-named hook can never leak in — and skips missing
    /// hooks (all three are optional). Returns false only when the hook
    /// RAN and raised — how the Controller detects a failed `init`.
    ///
    /// Per-tick allocation note: both symbols are pre-interned after the
    /// first call and dt is immediate, so steady-state hook dispatch
    /// creates no Ruby objects.
    pub fn callScriptHook(self: Vm, script_name: []const u8, hook: []const u8, dt: ?f32) bool {
        const mrb = self.mrb;
        const arena = c.labelle_mrb_gc_arena_save(mrb);
        defer c.labelle_mrb_gc_arena_restore(mrb, arena);

        const name_sym = c.mrb_intern(mrb, script_name.ptr, script_name.len);
        const hook_sym = c.mrb_intern(mrb, hook.ptr, hook.len);
        const args = [_]c.Value{
            c.Value.symbol(name_sym),
            c.Value.symbol(hook_sym),
            if (dt) |v| c.Value.float(v) else c.Value.nil(),
        };
        // Hooks are VM→script entries: stamp the current script so a
        // `Labelle.on` inside init/update attributes its handlers here.
        self.setCurrentScript(name_sym);
        const mod = c.Value.module(self.labelle_module);
        _ = c.mrb_funcall_argv(mrb, mod, self.sym_call_hook, args.len, &args);
        self.setCurrentScript(null);
        return !self.logPendingException(script_name);
    }

    /// Call a prelude function `Labelle.<name>` (no receiver-side lookup
    /// guards needed: the prelude defines every name the shared Controller
    /// calls; for backends without one — lua's controller-less prelude —
    /// the missing-method NoMethodError is swallowed by the lookup below).
    /// `dt` rides along when given. How the Controller triggers
    /// `dispatch_inbox` and the controller lifecycle sweeps.
    pub fn callLabelleFn(self: Vm, name: [*:0]const u8, dt: ?f32) void {
        const mrb = self.mrb;
        const arena = c.labelle_mrb_gc_arena_save(mrb);
        defer c.labelle_mrb_gc_arena_restore(mrb, arena);
        const span = std.mem.span(name);
        const fn_sym = c.mrb_intern(mrb, span.ptr, span.len);
        var args: [1]c.Value = .{if (dt) |v| c.Value.float(v) else c.Value.nil()};
        const argc: c.Int = if (dt != null) 1 else 0;
        const mod = c.Value.module(self.labelle_module);
        _ = c.mrb_funcall_argv(mrb, mod, fn_sym, argc, &args);
        _ = self.logPendingException("dispatch");
    }

    /// Stamp (or clear, with null) $__labelle_current_script. A Symbol,
    /// not a String: symbols are immediate values, so the per-entry stamp
    /// allocates nothing.
    fn setCurrentScript(self: Vm, name_sym: ?c.Sym) void {
        const v = if (name_sym) |s| c.Value.symbol(s) else c.Value.nil();
        c.mrb_gv_set(self.mrb, self.sym_current_script, v);
    }

    /// Call Labelle.<sym>(args...) and log (context-attributed) any
    /// exception it parks. Returns true when the call completed clean.
    fn callLabelleSym(self: Vm, fn_sym: c.Sym, args: []const c.Value, context: []const u8) bool {
        const mod = c.Value.module(self.labelle_module);
        _ = c.mrb_funcall_argv(self.mrb, mod, fn_sym, @intCast(args.len), args.ptr);
        return !self.logPendingException(context);
    }

    /// If mrb->exc holds a parked exception: format "<class>: <message>"
    /// plus its backtrace, route it through labelle_log, clear the slot,
    /// and return true. The formatting funcalls (message/backtrace) are
    /// themselves entries — a pathological exception object that raises
    /// from #message degrades to the class name alone rather than looping.
    fn logPendingException(self: Vm, context: []const u8) bool {
        const mrb = self.mrb;
        const exc = c.labelle_mrb_exc_get(mrb);
        if (exc.isNil()) return false;
        c.labelle_mrb_exc_clear(mrb);

        var buf: [ERROR_LOG_CAP]u8 = undefined;
        var w = std.Io.Writer.fixed(&buf);
        if (context.len > 0)
            w.print("[ruby] {s}: ", .{context}) catch {}
        else
            w.print("[ruby] ", .{}) catch {};
        w.print("{s}: ", .{c.mrb_obj_classname(mrb, exc)}) catch {};

        const msg = c.mrb_funcall_argv(mrb, exc, self.sym_message, 0, null);
        if (!c.labelle_mrb_exc_get(mrb).isNil()) {
            c.labelle_mrb_exc_clear(mrb);
            w.print("(message unavailable)", .{}) catch {};
        } else if (msg.tt == .string) {
            w.print("{s}", .{strSlice(msg)}) catch {};
        }

        // "\n  backtrace: name:3:in update | name:1" — the mruby analog of
        // lua's "stack traceback:" block, flattened to one log line.
        const bt = c.mrb_funcall_argv(mrb, exc, self.sym_backtrace, 0, null);
        if (!c.labelle_mrb_exc_get(mrb).isNil()) {
            c.labelle_mrb_exc_clear(mrb);
        } else if (bt.tt == .array and c.labelle_mrb_ary_len(bt) > 0) {
            w.print("\n  backtrace: ", .{}) catch {};
            const len = c.labelle_mrb_ary_len(bt);
            var i: c.Int = 0;
            while (i < len) : (i += 1) {
                const entry = c.mrb_ary_entry(bt, i);
                if (entry.tt != .string) continue;
                if (i > 0) w.print(" | ", .{}) catch {};
                w.print("{s}", .{strSlice(entry)}) catch {};
            }
        }

        const line = w.buffered();
        contract.labelle_log(line.ptr, line.len);
        return true;
    }
};

/// Borrowed view of an mruby String's bytes (valid while the value lives —
/// within one entry, under the arena save that anchors it).
pub fn strSlice(v: c.Value) []const u8 {
    const len: usize = @intCast(c.labelle_mrb_str_len(v));
    return c.labelle_mrb_str_ptr(v)[0..len];
}
